### ISSUE TITLE
Error, loginbutton not found

### ISSUE THREAD

**Issue by kelusk** [jcontini/fb-photo-downloader#15]
Dears,
I'm trying to use this project but something is going wrong. Probably the loginbutton id is changed?

Opening Browser...
get-tagged-photos.py:19: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=wd_options)

DevTools listening on ws://127.0.0.1:54967/devtools/browser/4b32f865-004c-4501-bdfc-9647773e2e2b
Logging In...
Traceback (most recent call last):
  File "get-tagged-photos.py", line 171, in <module>
    driver = start_session(args.u,args.p)
  File "get-tagged-photos.py", line 28, in start_session
    driver.find_element_by_id("loginbutton").click()
  File "C:\Users\mschiavi\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\mschiavi\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\mschiavi\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mschiavi\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="loginbutton"]"}
  (Session info: chrome=88.0.4324.150)

**Comment by eidorb** [comment]
It appears a different button id is generated for each request. 

Change [this line](https://github.com/jcontini/facebook-photos-download/blob/c161626a54a13f719ff3c0b76817f5125a4aa2f9/get-tagged-photos.py#L28) to the following:

            driver.find_element_by_css_selector('button[name=login]').click()

That will get you past the login page, only to face another error.

**Comment by eidorb** [comment]
I forked the repo thinking I'd make some minor changes, but ended up doing a full rewrite. 

https://github.com/eidorb/photos-of-me

**Comment by shohamjac** [comment]
I used your new fork and found you missed the capital letters in "View Full Size".

Except for this, it worked great.

**Comment by eidorb** [comment]
Thanks for the feedback. I think that issue could be solved with case-insensitive XPATH matching.
